# Scraping Yahoo Finance

## Week 7. Practice Programming Assignment 1

In this assignment you are required to look at historical data for 30 companies from [Dow Jones Index](https://en.wikipedia.org/wiki/Dow_Jones_Industrial_Average). Tickers for companies from the index can be found in *dow_jones_tickers.txt*. For each company you should get historical daily stock prices for 2019 from https://finance.yahoo.com/, and then use the data to answer the questions you will find below.

###### Import coursera grader tools

In [31]:
import sys
import numpy as np
sys.path.append("..")
import grading
grader = grading.Grader(assignment_key="FpZrXMbETcuStX7z6jFv2Q", 
                      all_parts=["RbP2k", "LLRai", "hgIbw", "Tx3OG", "Y05pG",
                                 "lFPeF", "htUtf", "Xri0I", "4JfUm", "oD7pP"])

In [115]:
# token expires every 30 min
COURSERA_EMAIL = "yatsi@edu.hse.ru"### YOUR EMAIL HERE
COURSERA_TOKEN = "4RPD2NBQetU4LEQy"### YOUR TOKEN

<br><br><br><br>

### Coding part

In [ ]:
# you can start your web-scraping here

In [14]:
dow_jones_companies = []

with open('dow_jones_tickers.txt') as f:
    for ticker in f:
        dow_jones_companies.append(ticker.strip())
import numpy as np 
np.array(dow_jones_companies)

array(['AXP', 'AAPL', 'BA', 'CAT', 'CSCO', 'CVX', 'XOM', 'GS', 'HD',
       'IBM', 'INTC', 'JNJ', 'KO', 'JPM', 'MCD', 'MMM', 'MRK', 'MSFT',
       'NKE', 'PFE', 'PG', 'TRV', 'UNH', 'RTX', 'VZ', 'V', 'WBA', 'WMT',
       'DIS', 'DOW'], dtype='<U4')

In [54]:
import yfinance as yf
data = pd.DataFrame()
for ticket in dow_jones_companies:
    print(ticket)
    stock = yf.download(ticket,'2019-01-01','2020-01-01')
    stock['ticket'] = ticket
    data = pd.concat([data, stock], axis=0)
data

AXP
[*********************100%***********************]  1 of 1 completed
AAPL
[*********************100%***********************]  1 of 1 completed
BA
[*********************100%***********************]  1 of 1 completed
CAT
[*********************100%***********************]  1 of 1 completed
CSCO
[*********************100%***********************]  1 of 1 completed
CVX
[*********************100%***********************]  1 of 1 completed
XOM
[*********************100%***********************]  1 of 1 completed
GS
[*********************100%***********************]  1 of 1 completed
HD
[*********************100%***********************]  1 of 1 completed
IBM
[*********************100%***********************]  1 of 1 completed
INTC
[*********************100%***********************]  1 of 1 completed
JNJ
[*********************100%***********************]  1 of 1 completed
KO
[*********************100%***********************]  1 of 1 completed
JPM
[*********************100%***********************]  1 of 1 completed
MCD
[*********************100%***********************]  1 of 1 completed
MMM
[*********************100%***********************]  1 of 1 completed
MRK
[*********************100%***********************]  1 of 1 completed
MSFT
[*********************100%***********************]  1 of 1 completed
NKE
[*********************100%***********************]  1 of 1 completed
PFE
[*********************100%***********************]  1 of 1 completed
PG
[*********************100%***********************]  1 of 1 completed
TRV
[*********************100%***********************]  1 of 1 completed
UNH
[*********************100%***********************]  1 of 1 completed
RTX
[*********************100%***********************]  1 of 1 completed
VZ
[*********************100%***********************]  1 of 1 completed
V
[*********************100%***********************]  1 of 1 completed
WBA
[*********************100%***********************]  1 of 1 completed
WMT
[*********************100%***********************]  1 of 1 completed
DIS
[*********************100%***********************]  1 of 1 completed
DOW
[*********************100%***********************]  1 of 1 completed

,Open,High,Low,Close,Adj Close,Volume,ticket
Date,,,,,,,
2019-01-02,93.910004,96.269997,93.769997,95.680000,92.643311,4175400,AXP
2019-01-03,94.790001,95.180000,93.230003,93.430000,90.834969,4776600,AXP
2019-01-04,95.370003,98.349998,94.900002,97.639999,94.928040,4637200,AXP
2019-01-07,97.769997,98.919998,97.019997,98.169998,95.443306,3289000,AXP
2019-01-08,98.690002,99.519997,97.519997,98.650002,95.909988,3227200,AXP
2019-01-09,98.739998,99.589996,98.150002,98.830002,96.084991,2954500,AXP
2019-01-10,98.449997,98.669998,97.820000,98.260002,95.530830,3523800,AXP
2019-01-11,97.879997,98.680000,97.360001,98.550003,95.812767,2770600,AXP
2019-01-14,97.760002,99.029999,97.620003,98.440002,95.705826,4120500,AXP
2019-01-15,98.610001,98.870003,97.739998,97.989998,95.268326,5795100,AXP
2019-01-16,98.940002,99.959999,98.510002,99.410004,96.648880,4701900,AXP
2019-01-17,99.410004,100.239998,98.570000,99.489998,96.726669,5693300,AXP
2019-01-18,98.190002,100.809998,96.370003,100.480003,97.689163,9872500,AXP
2019-01-22,99.849998,100.680000,98.959999,99.830002,97.057220,4699800,AXP
2019-01-23,99.930000,100.190002,98.459999,99.709999,96.940552,3585100,AXP
2019-01-24,99.690002,100.540001,99.379997,99.720001,96.950264,3415900,AXP
2019-01-25,100.430000,101.589996,100.089996,100.769997,97.971100,3488300,AXP
2019-01-28,100.050003,100.410004,99.480003,100.379997,97.591942,3185400,AXP
2019-01-29,100.940002,101.419998,100.540001,100.959999,98.155823,2827400,AXP
2019-01-30,101.089996,102.849998,100.540001,102.669998,99.818336,3501500,AXP
2019-01-31,102.000000,102.900002,101.699997,102.699997,99.847488,4302100,AXP
2019-02-01,102.410004,103.529999,102.410004,103.059998,100.197495,4727800,AXP
2019-02-04,103.040001,103.459999,102.519997,103.419998,100.547501,2578300,AXP
2019-02-05,103.629997,104.180000,103.410004,103.900002,101.014183,2231200,AXP
2019-02-06,103.849998,105.080002,103.430000,104.959999,102.044731,3595700,AXP
2019-02-07,104.059998,104.779999,103.610001,104.389999,101.490570,3857300,AXP
2019-02-08,103.730003,104.519997,103.430000,104.519997,101.616943,2581900,AXP
2019-02-11,104.949997,105.559998,104.809998,105.410004,102.482246,2653800,AXP
2019-02-12,106.269997,107.430000,106.260002,107.000000,104.028069,3238600,AXP
2019-02-13,107.550003,108.470001,107.099998,107.559998,104.572517,3182100,AXP
...,...,...,...,...,...,...,...
2019-11-18,54.750000,54.910000,54.119999,54.320000,51.047653,3439900,DOW
2019-11-19,54.810001,54.810001,52.790001,53.389999,50.173679,5208300,DOW
2019-11-20,53.139999,53.450001,52.099998,52.669998,49.497059,5394100,DOW
2019-11-21,52.709999,53.919998,52.349998,53.880001,50.634159,4618400,DOW
2019-11-22,53.980000,54.660000,53.599998,54.200001,50.934883,3115600,DOW
2019-11-25,54.820000,55.230000,54.360001,55.200001,51.874645,5073700,DOW
2019-11-26,55.250000,55.750000,54.820000,55.369999,52.034397,4643800,DOW
2019-11-27,54.680000,54.900002,53.900002,54.279999,51.663200,3926000,DOW
2019-11-29,54.009998,54.279999,53.119999,53.369999,50.797073,1887600,DOW
2019-12-02,53.000000,53.750000,52.889999,53.160000,50.597198,3349500,DOW
2019-12-03,51.959999,52.009998,51.049999,51.820000,49.321796,3950100,DOW
2019-12-04,53.490002,53.490002,52.209999,52.279999,49.759621,3791400,DOW
2019-12-05,52.529999,52.650002,51.680000,52.000000,49.493122,2692600,DOW
2019-12-06,52.590000,53.750000,52.590000,53.220001,50.654305,2818800,DOW
2019-12-09,53.959999,53.980000,52.990002,53.270000,50.701897,2377200,DOW
2019-12-10,53.360001,53.389999,52.689999,53.130001,50.568645,2609700,DOW
2019-12-11,53.500000,54.070000,53.049999,53.099998,50.540089,3253300,DOW
2019-12-12,53.250000,54.580002,52.820000,54.450001,51.825008,2882300,DOW
2019-12-13,54.639999,54.820000,53.250000,53.279999,50.711411,3198600,DOW
2019-12-16,53.610001,54.540001,53.509998,54.169998,51.558502,4040000,DOW
2019-12-17,54.099998,54.740002,53.930000,54.660000,52.024883,2665300,DOW
2019-12-18,54.360001,54.689999,53.540001,54.250000,51.634647,3659100,DOW
2019-12-19,54.430000,54.869999,54.060001,54.520000,51.891632,3356000,DOW
2019-12-20,55.049999,55.250000,54.020000,54.610001,51.977295,10476700,DOW
2019-12-23,54.490002,55.049999,54.220001,54.930000,52.281868,2678600,DOW
2019-12-24,55.000000,55.250000,54.650002,54.900002,52.253315,926200,DOW
2019-12-26,54.980000,55.230000,54.520000,55.220001,52.557884,1909600,DOW
2019-12-27,55.290001,55.549999,54.720001,54.830002,52.186687,1688500,DOW
2019-12-30,54.860001,55.049999,54.240002,54.340000,51.720310,1943300,DOW
2019-12-31,54.020000,54.779999,53.930000,54.730000,52.091507,2145700,DOW

In [55]:
price_changes = []
for ticket in dow_jones_companies:
    stock_data = data[data["ticket"]==ticket]
    price_change = (stock_data['Close'][-1]/stock_data['Open'][0]-1) * 100
    price_changes.append(price_change)
price_changes

[32.563084878249796,
 89.58615472504773,
 3.0266634777588175,
 19.067962693902764,
 13.434248981003027,
 12.269430079802301,
 3.6080183522342546,
 39.91966781097525,
 28.678331414483658,
 19.66787851955283,
 30.221931388900103,
 13.845305204350812,
 17.916489334166275,
 45.28400034413777,
 12.656060934247426,
 -6.069645783579647,
 20.799569454494748,
 58.412849938589304,
 39.181201105030624,
 -9.13728832167382,
 37.20751752254792,
 16.563111276107655,
 19.991841218909446,
 42.41156938341035,
 9.330487344558392,
 44.538456843449524,
 -12.261902139840908,
 29.681358718248397,
 33.792790864318654,
 3.7535536345712384]

In [59]:
price_change_df = pd.DataFrame()
price_change_df['ticket'] = dow_jones_companies
price_change_df['price_change'] = price_changes

<br><br>

### Questions

<br><br>

**Question 1.** What is the average change of price over the year (in %)?

*Note 1*. The opening price is the price at which a stock first trades upon the opening of an exchange on a trading day.

*Note 2*. The closing price for any stock is the final price at which it trades during regular market hours on any given day.

*Note 3*. Here by the price change we going to mean a ratio of a closing price in the last day of the period to an opening price in the first day of that period, subtracted one and multiplied by 100.

Example: if a price of a stock in day 1 opened at \\$100, and its close price in the last day was \\$120, then the price change during the period is: $$\left(\dfrac{120}{100}-1\right) * 100 = (1.2 - 1) * 100=20.$$

The price grew by 20%.

In [56]:
answer_part_1 = np.mean(price_changes)

In [57]:
# Setting our answers to grader. Do not change!
grader.set_answer("RbP2k", answer_part_1)

<br>

**Question 2.** What company's stock price grew the most (in %)? Enter ticker of the company as an answer)

In [82]:
price_change_df.sort_values('price_change', ascending=False).reset_index(drop=True)['ticket'].iloc[0]

'AAPL'

In [83]:
answer_part_2 = 'AAPL'

In [84]:
# Setting our answers to grader. Do not change!
grader.set_answer("LLRai", answer_part_2)

<br>

**Question 3.** What company's stock lost in price the most (in %)? Enter ticker of the company as an answer

In [70]:
answer_part_3 = price_change_df.sort_values('price_change', ascending=False).\
reset_index(drop=True)['ticket'].iloc[-1]

In [71]:
# Setting our answers to grader. Do not change!
grader.set_answer("hgIbw", answer_part_3)

<br>

**Question 4.** What company had the largest summary volume over the year? Enter ticker of the company as an answer

In [86]:
data.groupby('ticket').sum()['Volume'].reset_index().\
sort_values('Volume', ascending=False).reset_index(drop=True)['ticket'].iloc[0]

'AAPL'

In [76]:
answer_part_4 = 'AAPL'

In [77]:
# Setting our answers to grader. Do not change!
grader.set_answer("Tx3OG", answer_part_4)

<br>

**Question 5.** What is the biggest stock price daily increase (in %)? Enter the number

In [87]:
data['daily_ptc'] = (data['Close']/data['Open'] - 1) * 100
max(data['daily_ptc'])

7.741002936516583

In [88]:
answer_part_5 = 7.741002936516583

In [89]:
# Setting our answers to grader. Do not change!
grader.set_answer("Y05pG", answer_part_5)

<br><br>

**Question 6.** What is the company that had the biggest stock price daily increase? Enter ticker of the company as an answer

In [90]:
data[data['daily_ptc'] == max(data['daily_ptc'])]['ticket']

Date
2019-03-11    BA
Name: ticket, dtype: object

In [91]:
answer_part_6 =  'BA'

In [92]:
# Setting our answers to grader. Do not change!
grader.set_answer("lFPeF", answer_part_6)

<br>

**Question 7.** What is the biggest stock price daily decrease (in %)? Enter the number

In [93]:
answer_part_7 =  min(data['daily_ptc'])

In [94]:
# Setting our answers to grader. Do not change!
grader.set_answer("htUtf", answer_part_7)

<br>

**Question 8.** What is the company that had the biggest stock price daily decrese (in %)? Enter ticker of the company as an answer

In [95]:
data[data['daily_ptc'] == min(data['daily_ptc'])]['ticket']

Date
2019-04-16    UNH
Name: ticket, dtype: object

In [96]:
answer_part_8 = 'UNH'

In [97]:
# Setting our answers to grader. Do not change!
grader.set_answer("Xri0I", answer_part_8)

<br>

**Question 9.** What was the best month for all companies (i.e. average monthly price increase was the best)? Enter one of the following: January, February, March, April, May, June, July, August, September, October, November, December

In [109]:
#data = data.reset_index()

data['month'] = pd.DatetimeIndex(data['Date']).month

data.groupby("month").mean()['daily_ptc'].reset_index().sort_values("daily_ptc", ascending=False)

    month  daily_ptc
0       1   0.292917
1       2   0.168678
10     11   0.074571
3       4   0.049942
5       6   0.044545
4       5   0.040277
6       7  -0.005626
8       9  -0.009960
11     12  -0.025820
9      10  -0.029283
2       3  -0.038319
7       8  -0.178294

In [110]:
answer_part_9 = "January"

In [111]:
# Setting our answers to grader. Do not change!
grader.set_answer("4JfUm", answer_part_9)

<br>

**Question 10.** What was the worst month for all companies (i.e. average monthly price increase was the worst)? Enter one of the following: January, February, March, April, May, June, July, August, September, October, November, December

In [120]:
answer_part_10 = "May"

In [121]:
# Setting our answers to grader. Do not change!
grader.set_answer("oD7pP", answer_part_10)

<br>
<br>

### Submitting answers

In [122]:
# you can make submission with answers so far to check yourself at this stage
grader.submit(COURSERA_EMAIL, COURSERA_TOKEN)

Submitted to Coursera platform. See results on assignment page!